---

name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  Lint_Mix:
    name: Lint (Mix)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: docker-compose build

      - name: Format
        run: docker-compose run houston_server mix format

  Lint_Credo:
    name: Lint (Credo)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: docker-compose build

      - name: Lint
        run: docker-compose run houston_server mix credo --all

  Lint_Eslint:
    name: Lint (ESLint)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: docker-compose build

      - name: Lint
        run: docker-compose run -w /opt/app/assets houston_server npm run lint:js

  Lint_Stylelint:
    name: Lint (Stylelint)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: docker-compose build

      - name: Lint
        run: docker-compose run -w /opt/app/assets houston_server npm run lint:css

  Test_Unit:
    name: Test (Unit)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: docker-compose build

      - name: Test
        run: docker-compose run houston_server mix test.unit

  Test_Browser:
    name: Test (Browser)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: docker-compose build

      - name: Build
        run: docker-compose run -w /opt/app/assets houston_server npm run build

      - name: Test
        run: docker-compose run houston_server mix test.browser

  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: docker build -f Dockerfile-production .
