---

name: Publish

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  Lint_Mix:
    name: Lint (Mix)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: docker-compose build

      - name: Format
        run: docker-compose run houston_server mix format

  Lint_Credo:
    name: Lint (Credo)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: docker-compose build

      - name: Lint
        run: docker-compose run houston_server mix credo --all

  Lint_Eslint:
    name: Lint (ESLint)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: docker-compose build

      - name: Lint
        run: docker-compose run -w /opt/app/assets houston_server npm run lint:js

  Lint_Stylelint:
    name: Lint (Stylelint)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: docker-compose build

      - name: Lint
        run: docker-compose run -w /opt/app/assets houston_server npm run lint:css

  Test_Unit:
    name: Test (Unit)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: docker-compose build

      - name: Test
        run: docker-compose run houston_server mix test.unit

  Test_Browser:
    name: Test (Browser)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: docker-compose build

      - name: Build
        run: docker-compose run -w /opt/app/assets houston_server npm run build

      - name: Test
        run: docker-compose run houston_server mix test.browser

  Publish:
    runs-on: ubuntu-latest

    needs:
      - Lint_Mix
      - Lint_Credo
      - Lint_Eslint
      - Lint_Stylelint
      - Test_Unit
      - Test_Browser

    env:
      DOCKER_IMAGE: docker.pkg.github.com/${{ github.repository }}/houston-server:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          docker build -f Dockerfile-production -t $DOCKER_IMAGE .

      - name: Publish
        run: |
          docker login -u elementaryBot -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
          docker push $DOCKER_IMAGE

  Deploy:
    runs-on: ubuntu-latest

    needs:
      - Publish

    steps:
      - name: Setup kubectl
        uses: azure/setup-kubectl@v1

      - name: Deploy
        run: >
          echo "${{ secrets.KUBE_CERT }}" | base64 -d  > /tmp/elementary.crt

          kubectl \
            --server="${{ secrets.KUBE_SERVER }}" \
            --certificate-authority="/tmp/elementary.crt" \
            --token="${{ secrets.KUBE_TOKEN }}" \
            --namespace="houston" \
            rollout restart deployment houston-server
